server {
    listen 5500;

    root /usr/share/nginx/html;
    index index.html;

    # Archivos estáticos
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Compresión
    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
}
